### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by rishiosaur** [Standard-Structure/Standard-Structure#1]
It'd be pretty cool to have a CLI that could pull a certain project template for a language or framework to a user's computer. If @Matt-Gleich is up for it, I could certainly try to give it a shot!

**Comment by Matt-Gleich** [comment]
That would be super awesome! You gonna make a repo for it or do think I should form an organization for this?

**Comment by rishiosaur** [comment]
I think an organization would be pretty beneficial.

**Comment by Matt-Gleich** [comment]
Created CLI repo:
https://github.com/Standard-Structure/CLI
