### ISSUE TITLE
Twitter Int.

### ISSUE THREAD

**Issue by sampoder** [Standard-Structure/Standard-Structure#15]
Could make a twitter bot that posts for every need addition

**Comment by Matt-Gleich** [comment]
Every need addition? You mean like when an issue is created?

**Comment by sampoder** [comment]
like every time a new structure is posted

**Comment by sampoder** [comment]
wow need addition, meant new addition

**Comment by Matt-Gleich** [comment]
That could be cool! Do you wanna be added to the org so you can make a repo for it?

**Comment by sampoder** [comment]
sure

-- 
This email and any attachments are confidential and may also be privileged. 
If you have received this message in error, please (a) notify the sender 
immediately, (b) destroy this email and any attachments, and (c) do not 
use, copy, store and/or disclose to any person this email and any 
attachments. The sender gives no representation or guarantee with respect 
to the integrity of any emails or attached files and the recipient should 
check the integrity of and scan this email and any attached files for 
viruses prior to opening.

**Comment by sampoder** [comment]
sure

**Comment by Matt-Gleich** [comment]
You should run it in a github action on every push to master
