### ISSUE TITLE
CLI for adding structures

### ISSUE THREAD

**Issue by Matt-Gleich** [Standard-Structure/Standard-Structure#21]
Make a CLI for adding a structure. Streamlines the contribution process by creating a skeleton for the structure.

**Comment by Matt-Gleich** [comment]
@rishiosaur Should this be part of the CLI we are already making or a simple python script bundles with this repo?

**Comment by rishiosaur** [comment]
@Matt-Gleich I think we should bundle it together with the repo. It's what we do over at Exercism, and it's worked pretty well so far.

**Comment by rishiosaur** [comment]
It doesn't have to be huge; I think we can just build it in Rust and make it an executable

**Comment by Matt-Gleich** [comment]
Do you know go? I would rather make it with that because I have more experience with it. If anything I would wanna make it with python and make that an executable which it looks like you can do with something called PyInstaller

**Comment by rishiosaur** [comment]
@Matt-Gleich Either one works, it's your call.

**Comment by Matt-Gleich** [comment]
Most Linux and macOS installs have python anyways and it's not like its a rare language. I think it just makes sense to make it a simple python script.
