### ISSUE TITLE
Look at alternative for icons

### ISSUE THREAD

**Issue by Matt-Gleich** [Standard-Structure/Standard-Structure#38]
The current use of emojis for icons isn't super scalable as frameworks or languages can have conflicting icons. Maybe use inline images?

**Comment by cjdenio** [comment]
Inline images seems like the best option. Can you scale images down in Markdown?

**Comment by Matt-Gleich** [comment]
https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown

**Comment by Matt-Gleich** [comment]
This should be part of the PR that refactors everything (#34)

**Comment by cjdenio** [comment]
We could use [Shields](https://shields.io) to create static badges to put on the README.
Like this:

![Language: Dart](https://img.shields.io/static/v1?label=Language&message=Dart&color=0175C2&logo=dart&logoColor=white&style=for-the-badge)

![Framework: Vue](https://img.shields.io/static/v1?label=Framework&message=Vue&color=4FC08D&logo=vue.js&logoColor=white&style=for-the-badge)
![Framework: Deno](https://img.shields.io/static/v1?label=Framework&message=Deno&color=black&logo=deno&logoColor=white&style=for-the-badge)

**Comment by Matt-Gleich** [comment]
Looks good @cjdenio! Can you use the badge variation that matches the CI badges that GitHub makes? I think these look a little big. What do you think @Cal-Hagner?

**Comment by Cal-Hagner** [comment]
I think the badges look fine as is.

**Comment by Matt-Gleich** [comment]
Ok sounds good! Let's refactor them!

**Comment by cjdenio** [comment]
Should we put these in the TOC headers, or just remove the emoji?

**Comment by Cal-Hagner** [comment]
I think anywhere that we're currently using emoji + names should be replaced with just these badges.

**Comment by cjdenio** [comment]
Note: https://simpleicons.org (the icon library that Shields uses) actually suggests background colors, so let's try to use those.

![image](https://user-images.githubusercontent.com/34525547/82825293-f90f1200-9e78-11ea-8924-0da285134670.png)

**Comment by cjdenio** [comment]
How does this look?
https://git.io/JfVMw

**Comment by Matt-Gleich** [comment]
Looks good!

**Comment by rishiosaur** [comment]
Can you set them as links to the structure folders @cjdenio?

**Comment by rishiosaur** [comment]
Other than that, I think they look awesome! We could even have a little description of each next to them.
