### ISSUE TITLE
Add PR templates

### ISSUE THREAD

**Issue by Matt-Gleich** [Standard-Structure/Standard-Structure#5]

**Comment by Cal-Hagner** [comment]
@Matt-Gleich What templates were you thinking for this? I'm thinking one for framework/language additions and one for bug reports, then one standard one that asks for the resolved issue, etc. How does that sound?

**Comment by rishiosaur** [comment]
@Cal-Hagner I really like that idea. I'll take a crack at it rn

**Comment by Matt-Gleich** [comment]
Yep sounds good!

**Comment by Cal-Hagner** [comment]
@rishiosaur @Matt-Gleich After [reading about PR templates](https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) and checking out a [bunch of examples](https://github.com/devspace/awesome-github-templates#rocket-templates-for-pull-requests), it seems that multiple PR templates is harder to do, and they're really [only usable via template queries in the URL](https://help.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters#filling-issues-and-pull-requests-with-custom-templates). It may be easier just to do one PR that has a checkbox and conditionally used sections for bug report vs. framework/language additions. I'll open up a PR for that template in a few minutes. I'm going to use [this fun generator](https://www.talater.com/open-source-templates/#/) to get a basic draft and then modify it based on our needs.

**Comment by rishiosaur** [comment]
Sounds good, @Cal-Hagner! Add me as a reviewer once you’re ready.
