### ISSUE TITLE
🖼️ Framework Request: Deno

### ISSUE THREAD

**Issue by Matt-Gleich** [Standard-Structure/Standard-Structure#7]
| Question                                   | ✅ Yes | ❌ No |
|--------------------------------------------|-------|------|
| Is this framework already being requested? | - [ ]    | - [ x ]   |

### What is the name of the framework?

Deno

### What language does the framework use?

TypeScript or JavaScript

### What is the website for the framework?

deno.land

**Comment by cjdenio** [comment]
The checkboxes aren't rendering for me. 🤔 
![image](https://user-images.githubusercontent.com/34525547/82488679-4b81b480-9aae-11ea-806b-82e41e080b84.png)

**Comment by Matt-Gleich** [comment]
Same, I guess they just don't render them inside tables 🤷
