### ISSUE TITLE
🖼️ Framework Request: Node

### ISSUE THREAD

**Issue by Matt-Gleich** [Standard-Structure/Standard-Structure#9]
| Question                                   | ✅ Yes | ❌ No |
|--------------------------------------------|-------|------|
| Is this framework already being requested? | []    | [x]   |

### What is the name of the framework?

node

### What language does the framework use?

JavaScript

### What is the website for the framework?

nodejs.org

**Comment by rishiosaur** [comment]
I don't think the `basic` folder should contain a lot; just an `src/` folder, `index.js`, and the minimum required for npm.
